abbr -a -U -- gaa 'git add .'
abbr -a -U -- gcmsg 'git commit -m ""'
abbr -a -U -- ggpush 'git push origin master'
abbr -a -U -- go 'cd ~/dev/todohub'
abbr -a -U -- gorun 'cd ~/dev/todohub && npm run dev'
abbr -a -U -- gprun 'cd dev/todohub && npm run dev'
