abbr -a -U -- gaa 'git add .'
abbr -a -U -- gcmsg 'git commit -m'
abbr -a -U -- ggpull 'git pull origin master'
abbr -a -U -- ggpush 'git push origin master'
abbr -a -U -- go 'cd ~/dev/todohub'
abbr -a -U -- gorun 'go && npm run dev'
